In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/paradox-ml-challenge/sample_submission.csv
/kaggle/input/paradox-ml-challenge/train.csv
/kaggle/input/paradox-ml-challenge/test.csv


In [2]:
import tensorflow as tf
from transformers import TFAutoModel, AutoTokenizer
from datasets import load_dataset


In [3]:
model = TFAutoModel.from_pretrained("bert-base-multilingual-uncased")

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/672M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [4]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-multilingual-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.72M [00:00<?, ?B/s]

/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [5]:
inputs = tokenizer(['Hello', 'Hi'], padding=True, truncation=True,
                  return_tensors='tf')
inputs

{'input_ids': <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  101, 29155,   102],
       [  101, 11463,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>}

In [6]:
output = model(inputs)
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(2, 3, 768), dtype=float32, numpy=
array([[[-0.05943973, -0.0388563 ,  0.00211452, ..., -0.00146032,
         -0.00854838,  0.0153379 ],
        [ 0.29476446,  0.57224274, -0.02179924, ..., -0.16828552,
          0.24520567, -0.48434696],
        [-0.11420213,  0.67099065, -0.491777  , ...,  0.5322751 ,
          0.48515928, -0.93350494]],

       [[ 0.05577382,  0.00608706,  0.06541577, ..., -0.01034853,
          0.00489283, -0.04098387],
        [ 0.09404232,  0.71167755,  0.3421103 , ...,  0.06967992,
         -0.03429259, -0.5540221 ],
        [-0.12899154,  0.7875171 ,  0.3617646 , ...,  0.4788404 ,
          0.16644579, -0.9128005 ]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[ 0.07195359,  0.06592104,  0.1317121 , ...,  0.02932431,
        -0.19124438, -0.16242865],
       [ 0.14824475,  0.04399505,  0.18804589, ...,  0.09633423,
        -0.19378375,

In [7]:
he=pd.read_csv('/kaggle/input/paradox-ml-challenge/train.csv')
he

Comment       Label
0       last proof me  kaha gaya little confused about it       doubt
1                            sir g ki value positive hogi       doubt
2                                  like the video guyssss  irrelevant
3                             ummm sir i want see ur wife  irrelevant
4       physics wallah punabi mundamundi mein thusde d...  irrelevant
...                                                   ...         ...
213742                             superb performance sir    feedback
213743                                           mja aaya    feedback
213744                           blocks wala sum be padao    feedback
213745                    uminima stable umaxima unstable    feedback
213746  sir you and namo sir get best physics teacher ...    feedback

[213747 rows x 2 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
he['label'] = label_encoder.fit_transform(he['Label'])
he

Comment       Label  label
0       last proof me  kaha gaya little confused about it       doubt      0
1                            sir g ki value positive hogi       doubt      0
2                                  like the video guyssss  irrelevant      2
3                             ummm sir i want see ur wife  irrelevant      2
4       physics wallah punabi mundamundi mein thusde d...  irrelevant      2
...                                                   ...         ...    ...
213742                             superb performance sir    feedback      1
213743                                           mja aaya    feedback      1
213744                           blocks wala sum be padao    feedback      1
213745                    uminima stable umaxima unstable    feedback      1
213746  sir you and namo sir get best physics teacher ...    feedback      1

[213747 rows x 3 columns]

In [9]:
he.to_csv("training.csv",index=False)

In [10]:
import pandas as pd
from datasets import Dataset, DatasetDict
from sklearn.model_selection import train_test_split

df = pd.read_csv("/kaggle/working/training.csv")

# Step 1: Split the DataFrame into train and test sets (90% train, 20% test)
train_df, test_df = train_test_split(df, test_size=0.1, random_state=42,shuffle=True)

# Step 2: Further split the training set into training and validation sets (80% train, 20% validation)
train_df, val_df = train_test_split(train_df, test_size=0.2, random_state=42)  # Now 64% train, 16% validation

# Step 3: Convert each DataFrame to a Hugging Face Dataset
train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)
test_dataset = Dataset.from_pandas(test_df)

# Step 4: Create a DatasetDict to hold the datasets
emotions = DatasetDict({
    'train': train_dataset,
    'validation': val_dataset,
    'test': test_dataset
})




In [11]:
emotions

DatasetDict({
    train: Dataset({
        features: ['Comment', 'Label', 'label', '__index_level_0__'],
        num_rows: 153897
    })
    validation: Dataset({
        features: ['Comment', 'Label', 'label', '__index_level_0__'],
        num_rows: 38475
    })
    test: Dataset({
        features: ['Comment', 'Label', 'label', '__index_level_0__'],
        num_rows: 21375
    })
})

In [12]:
for split in emotions.keys():
    emotions[split] = emotions[split].remove_columns('__index_level_0__')


In [13]:
emotions

DatasetDict({
    train: Dataset({
        features: ['Comment', 'Label', 'label'],
        num_rows: 153897
    })
    validation: Dataset({
        features: ['Comment', 'Label', 'label'],
        num_rows: 38475
    })
    test: Dataset({
        features: ['Comment', 'Label', 'label'],
        num_rows: 21375
    })
})

In [14]:
def tokenize(batch):
    return tokenizer(batch["Comment"], padding=True, truncation=True)

In [15]:
emotions_encoded = emotions.map(tokenize, batched=True, batch_size=None)

Map:   0%|          | 0/153897 [00:00<?, ? examples/s]

Map:   0%|          | 0/38475 [00:00<?, ? examples/s]

Map:   0%|          | 0/21375 [00:00<?, ? examples/s]

In [16]:
emotions_encoded

DatasetDict({
    train: Dataset({
        features: ['Comment', 'Label', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 153897
    })
    validation: Dataset({
        features: ['Comment', 'Label', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 38475
    })
    test: Dataset({
        features: ['Comment', 'Label', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 21375
    })
})

In [17]:
# setting 'input_ids', 'attention_mask', 'token_type_ids', and 'label'
# to the tensorflow format. Now if you access this dataset you will get these
# columns in `tf.Tensor` format

emotions_encoded.set_format('tf', 
                            columns=['input_ids', 'attention_mask', 'token_type_ids', 'label'])

# setting BATCH_SIZE to 64.
BATCH_SIZE = 8

def order(inp):
    '''
    This function will group all the inputs of BERT
    into a single dictionary and then output it with
    labels.
    '''
    data = list(inp.values())
    return {
        'input_ids': data[1],
        'attention_mask': data[2],
        'token_type_ids': data[3]
    }, data[0]

# converting train split of `emotions_encoded` to tensorflow format
train_dataset = tf.data.Dataset.from_tensor_slices(emotions_encoded['train'][:])
# set batch_size and shuffle
train_dataset = train_dataset.batch(BATCH_SIZE).shuffle(1000)
# map the `order` function
train_dataset = train_dataset.map(order, num_parallel_calls=tf.data.AUTOTUNE)

# ... doing the same for test set ...
test_dataset = tf.data.Dataset.from_tensor_slices(emotions_encoded['test'][:])
test_dataset = test_dataset.batch(BATCH_SIZE)
test_dataset = test_dataset.map(order, num_parallel_calls=tf.data.AUTOTUNE)

In [18]:
inp, out = next(iter(train_dataset)) # a batch from train_dataset
print(inp, '\n\n', out)

{'input_ids': <tf.Tensor: shape=(8, 512), dtype=int64, numpy=
array([[  101, 10140, 10123, ...,     0,     0,     0],
       [  101,   163, 10320, ...,     0,     0,     0],
       [  101, 10160, 12979, ...,     0,     0,     0],
       ...,
       [  101, 10253, 10150, ...,     0,     0,     0],
       [  101, 16371, 27666, ...,     0,     0,     0],
       [  101, 12810, 15768, ...,     0,     0,     0]])>, 'attention_mask': <tf.Tensor: shape=(8, 512), dtype=int64, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])>, 'token_type_ids': <tf.Tensor: shape=(8, 512), dtype=int64, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])>} 

 tf.Tensor([1 1 1 2 2 1 1 2], shape=(8,

In [19]:
class BERTForClassification(tf.keras.Model):
    
    def __init__(self, bert_model, num_classes):
        super().__init__()
        self.bert = bert_model
        self.fc = tf.keras.layers.Dense(num_classes, activation='softmax')
        
    def call(self, inputs):
        x = self.bert(inputs)[1]
        return self.fc(x)

In [20]:
classifier = BERTForClassification(model, num_classes=3)

classifier.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=['accuracy']
)

In [21]:
history = classifier.fit(
    train_dataset,
    epochs=2
)

Epoch 1/2


I0000 00:00:1730054894.892870      70 service.cc:145] XLA service 0x7ce424335160 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1730054894.892928      70 service.cc:153]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
I0000 00:00:1730054894.892934      70 service.cc:153]   StreamExecutor device (1): Tesla T4, Compute Capability 7.5
I0000 00:00:1730054895.070482      70 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


19238/19238 [==============================] - 19569s 1s/step - loss: 0.7050 - accuracy: 0.6875
Epoch 2/2
19238/19238 [==============================] - 19471s 1s/step - loss: 0.6260 - accuracy: 0.7297


In [22]:
classifier.evaluate(test_dataset)

2672/2672 [==============================] - 918s 339ms/step - loss: 0.6385 - accuracy: 0.7258


[0.638484537601471, 0.7258479595184326]